trainer:
  name: Trainer
  num_epochs: 10
  output_dir: experiments/cifar10

model:
  name: efficientnet_b0
  num_classes: 10

dataset:
  name: CIFAR10DataLoader
  root: data
  batch_size: 16
  image_size: 224
  num_workers: 16

optimizer:
  name: SGD
  lr: 1.25e-2


scheduler:
  name: MultiStepLR
  milestones: [30, 60, 80]
  gamma: 0.1
