dataset:
  batch_size: 16
  image_size: 224
  name: CIFAR10DataLoader
  num_workers: 16
  root: data
model:
  name: efficientnet_b1
  num_classes: 10
optimizer:
  lr: 0.0015
  name: Adam
scheduler:
  gamma: 0.1
  milestones:
  - 3
  - 6
  - 8
  name: MultiStepLR
trainer:
  name: Trainer
  num_epochs: 10
  output_dir: experiments/cifar10-cpu0
